---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /home/srinivas/anaconda3/bin/python3.11
  tasks:
    - name: Pull image
      docker_image:
        name: manda1234/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name Calculator manda1234/calculator